// data.js
const cardSection = {
    title: 'Sample Books Generated by BookAI',
    description: 'Explore some of the captivating books created using our AI technology.',
    cards: [
        {
            id: 1,
            image: 'https://raw.githubusercontent.com/adarshagupta/trybookai/main/public-assets/paradox.png',
            title: 'Science Fiction',
            description: 'As Dr. Elara stepped through the shimmering portal, she knew there was no turning back. The fate of two universes now rested in her hands and',
        },
        {
            id: 2,
            image: 'https://raw.githubusercontent.com/adarshagupta/trybookai/main/public-assets/mist.png',
            title: 'Mystery',
            description: 'The old lighthouse stood silent, its beacon long extinguished. But on foggy nights, some swore they could still see its ghostly light and',
        },
        {
            id: 3,
            image: 'https://raw.githubusercontent.com/adarshagupta/trybookai/main/public-assets/ecos.png',
            title: 'Fantasy',
            description: 'The ancient prophecy spoke of a child born with starlight in their eyes. As the comet blazed overhead, the kingdom held its breath and',
        },
    ],
};

export default cardSection;
